Przygotowanie danych
```{r}
setwd("D:/PW-MAGISTERSKIE/PW-Magisterskie-sem2/ZUM/Projekt/ZUM_Proj")
df <- read.csv(
  file = 'Data/winemag-data-130k-v2.csv',
  sep = ','
)

df2 <- df[,colSums(is.na(df["description"]))<nrow(df)]
df2[["description"]] <- tolower(df2[["description"]])

library(stringr)
df2[["description"]] <-str_replace(gsub("([^a-z'])", " ", df2[["description"]]), "B", "b") 
df2[["description"]] <-str_replace(gsub("\\s+", " ", df2[["description"]]), "B", "b") 
df2[["description"]] <-str_replace(gsub("\\s$", "", df2[["description"]]), "B", "b")


#Sprawdzanie
df2[29996,"description"]
df[29996,"description"]
df2[502,"description"]
df[502,"description"]
```
Klasy ze wsględu na points
```{r}
dyskretyzacja <- function(x) {
  if(x<82) {
    1
  }
  else if(x<84) {
    2
  }
  else if(x<86) {
    3
  }
  else if(x<88) {
    4
  }
  else{
    5
  }
}

df2$points<-apply(array(df2[["points"]]),MARGIN=1, FUN=dyskretyzacja)
```

Podział danych (Przy uczeniu na naszych danych)


```{r}
#
library(data.table)
#library(magrittr)
#data("df2")
setDT(df2)
setkey(df2, X)
set.seed(2017L)
all_ids = df2$X
#train_ids = sample(all_ids, 4000)
#test_ids = setdiff(all_ids, train_ids)
train_ids = setdiff(all_ids, -1)
train = df2[J(train_ids)]
#test = df2[J(test_ids)]

```

Robienie słownika z wykorzystaniem tokenóW (bardziej użyteczne, tokeny są spoko- matrix w kolumnie 'value' ma listę słóW)

```{r}
library(text2vec)
tok_fun = word_tokenizer
train_tokens = tok_fun(train$description)


it_train = itoken(train_tokens,
                  ids = train$X,
                  # turn off progressbar because it won't look nice in rmd
                  progressbar = FALSE)

stop_words <- c("i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", "don", "should", "now")
# stopwords

vocab = create_vocabulary(it_train, stopwords = stop_words)
vocab[order(-vocab$doc_count),]
```
 
TF-IDF (Advanced Bag of Words)

```{r}
  
pruned_vocab = prune_vocabulary(vocab,
                                term_count_min = length(train_tokens)*0.05,
                                doc_proportion_max = 0.5,
                                doc_proportion_min = 0.001)
vectorizer = vocab_vectorizer(pruned_vocab)
dtm_train = create_dtm(it_train, vectorizer)
   
```

# ```{r}
# h_vectorizer = hash_vectorizer(hash_size = 2 ^ 14)
# 
# t1 = Sys.time()
# dtm_train = create_dtm(it_train, h_vectorizer)
# print(difftime(Sys.time(), t1, units = 'sec'))
# ```


```{r}
#vectorizer = vocab_vectorizer(vocab)


# definicja tfidf modelu
tfidf = TfIdf$new()
# fit model to train data and transform train data with fitted model
dtm_train_tfidf = fit_transform(dtm_train, tfidf)
# tfidf modified by fit_transform() call!

# apply pre-trained tf-idf transformation to test data
#test_tokens = tok_fun(test$description)

#it_test = itoken(test_tokens,
#                 ids = test$X,
#                 progressbar = FALSE)


#dtm_test = create_dtm(it_test, vectorizer)
#dtm_test_tfidf = transform(dtm_test, tfidf)
```

```{r}
dtm_train_tfidf_matrix <- as.matrix(dtm_train)
dtm_train_tfidf_df <- as.data.frame(dtm_train_tfidf_matrix)
```


```{r}
library(text2vec)
library(caret)
ctrl.svm.1 <- trainControl(method="repeatedcv",
                           number=10,
                           repeats=5,
                           summaryFunction = multiClassSummary,
                           verboseIter = TRUE)
fit.svm.1 <- train(x = dtm_train_tfidf_df, y= as.factor(train$points), 
                   method="svmLinear2",  
                   metric="Accuracy", 
                   trControl = ctrl.svm.1, 
                   scale = FALSE, verbose = TRUE)
```


